In [53]:
import pandas as pd
import numpy as np
import os
import re

In [19]:
df = pd.read_excel("Data/V300Case1CutFre20.xls")

In [20]:
df.head()

   5.008333e+01  1.866823e-15  4.667057e-22  0.000000e+00
0     50.166667 -7.744571e-11 -1.935956e-17  5.514080e-10
1     50.250000 -1.349730e-09 -4.148745e-16  9.609213e-09
2     50.333333 -1.174509e-08 -4.440889e-15  8.362515e-08
3     50.416667 -6.850940e-08 -3.180423e-14  4.878649e-07
4     50.500000 -3.032823e-07 -1.721791e-13  2.160162e-06

In [21]:
df.shape[0]

17400

In [17]:
cut_idx= int(df.shape[0]*0.05)

In [22]:
df = df.iloc[cut_idx:df.shape[0]-cut_idx]

In [23]:
df.shape

(15660, 4)

In [24]:
a = [1,2,3,5]

In [62]:
os.listdir('./Data/')

['V380Case26CutFre20.xls',
 'V300Case3CutFre100.xls',
 'V350Case26CutFre20.xls',
 'V350Case19CutFre150.xls',
 'V350Case33CutFre100.xls',
 'V380Case14CutFre150.xls',
 'V380Case17CutFre50.xls',
 'V350Case17CutFre50.xls',
 'V380Case35CutFre200.xls',
 'V350Case8CutFre100.xls',
 'V380Case8CutFre100.xls',
 'V380Case20CutFre200.xls',
 'V300Case29CutFre150.xls',
 'V380Case38CutFre100.xls',
 'V350Case36CutFre20.xls',
 'V380Case36CutFre20.xls',
 'V350Case12CutFre50.xls',
 'V380Case5CutFre200.xls',
 'V380Case12CutFre50.xls',
 'V350Case5CutFre200.xls',
 'V380Case10CutFre200.xls',
 'V300Case33CutFre100.xls',
 'V300Case19CutFre150.xls',
 'V380Case11CutFre20.xls',
 'V350Case11CutFre20.xls',
 'V350Case29CutFre150.xls',
 'V380Case24CutFre150.xls',
 'V350Case24CutFre150.xls',
 'V380Case7CutFre50.xls',
 'V300Case20CutFre200.xls',
 'V300Case6CutFre20.xls',
 'V380Case29CutFre150.xls',
 'V350Case3CutFre100.xls',
 'V300Case26CutFre20.xls',
 'V380Case3CutFre100.xls',
 'V300Case35CutFre200.xls',
 'V350Case6CutFre20.xls',
 'V300Case14CutFre150.xls',
 'V350Case10CutFre200.xls',
 'V300Case8CutFre100.xls',
 'V300Case17CutFre50.xls',
 'V350Case38CutFre100.xls',
 'V350Case20CutFre200.xls',
 'V300Case24CutFre150.xls',
 'V380Case1CutFre20.xls',
 'V300Case5CutFre200.xls',
 'V300Case12CutFre50.xls',
 'V300Case36CutFre20.xls',
 'V350Case35CutFre200.xls',
 'V380Case33CutFre100.xls',
 'V300Case10CutFre200.xls',
 'V350Case14CutFre150.xls',
 'V380Case2CutFre50.xls',
 'V380Case19CutFre150.xls',
 'V300Case11CutFre20.xls',
 'V300Case38CutFre100.xls',
 'V350Case18CutFre100.xls',
 'V350Case25CutFre200.xls',
 'V350Case7CutFre50.xls',
 'V300Case34CutFre150.xls',
 'V300Case16CutFre20.xls',
 'V350Case30CutFre200.xls',
 'V300Case32CutFre50.xls',
 'V300Case27CutFre50.xls',
 'V300Case15CutFre200.xls',
 'V300Case40CutFre200.xls',
 'V300Case28CutFre100.xls',
 'V380Case6CutFre20.xls',
 'V300Case7CutFre50.xls',
 'V380Case9CutFre150.xls',
 'V350Case9CutFre150.xls',
 'V380Case23CutFre100.xls',
 'V300Case31CutFre20.xls',
 'V350Case1CutFre20.xls',
 'V300Case2CutFre50.xls',
 'V300Case18CutFre100.xls',
 'V300Case22CutFre50.xls',
 'V300Case25CutFre200.xls',
 'V300Case4CutFre150.xls',
 'V380Case39CutFre150.xls',
 'V300Case30CutFre200.xls',
 'V380Case13CutFre100.xls',
 'V350Case34CutFre150.xls',
 'V300Case1CutFre20.xls',
 'V350Case2CutFre50.xls',
 'V350Case15CutFre200.xls',
 'V350Case40CutFre200.xls',
 'V350Case28CutFre100.xls',
 'V300Case21CutFre20.xls',
 'V300Case37CutFre50.xls',
 'V380Case32CutFre50.xls',
 'V350Case32CutFre50.xls',
 'V380Case16CutFre20.xls',
 'V300Case23CutFre100.xls',
 'V350Case16CutFre20.xls',
 'V380Case28CutFre100.xls',
 'V380Case15CutFre200.xls',
 'V380Case40CutFre200.xls',
 'V350Case13CutFre100.xls',
 'V350Case31CutFre20.xls',
 'V300Case9CutFre150.xls',
 'V380Case34CutFre150.xls',
 'V380Case31CutFre20.xls',
 'V350Case39CutFre150.xls',
 'V380Case27CutFre50.xls',
 'V350Case27CutFre50.xls',
 'V350Case23CutFre100.xls',
 'V380Case4CutFre150.xls',
 'V350Case4CutFre150.xls',
 'V350Case22CutFre50.xls',
 'V380Case22CutFre50.xls',
 'V300Case39CutFre150.xls',
 'V350Case37CutFre50.xls',
 'V300Case13CutFre100.xls',
 'V380Case30CutFre200.xls',
 'V380Case37CutFre50.xls',
 'V380Case21CutFre20.xls',
 'V350Case21CutFre20.xls',
 'V380Case25CutFre200.xls',
 'V380Case18CutFre100.xls']

In [63]:
files = [f for f in os.listdir('./Data/') if re.match(r'.*Fre20.xls', f)]

In [64]:
files

['V380Case26CutFre20.xls',
 'V350Case26CutFre20.xls',
 'V350Case36CutFre20.xls',
 'V380Case36CutFre20.xls',
 'V380Case11CutFre20.xls',
 'V350Case11CutFre20.xls',
 'V300Case6CutFre20.xls',
 'V300Case26CutFre20.xls',
 'V350Case6CutFre20.xls',
 'V380Case1CutFre20.xls',
 'V300Case36CutFre20.xls',
 'V300Case11CutFre20.xls',
 'V300Case16CutFre20.xls',
 'V380Case6CutFre20.xls',
 'V300Case31CutFre20.xls',
 'V350Case1CutFre20.xls',
 'V300Case1CutFre20.xls',
 'V300Case21CutFre20.xls',
 'V380Case16CutFre20.xls',
 'V350Case16CutFre20.xls',
 'V350Case31CutFre20.xls',
 'V380Case31CutFre20.xls',
 'V380Case21CutFre20.xls',
 'V350Case21CutFre20.xls']

In [67]:
def get_files(pattern,path="Data"):
    files = [f for f in os.listdir(path) if re.match(pattern, f)]
    return files

In [68]:
get_files(r'.*Fre20.xls')

['V380Case26CutFre20.xls',
 'V350Case26CutFre20.xls',
 'V350Case36CutFre20.xls',
 'V380Case36CutFre20.xls',
 'V380Case11CutFre20.xls',
 'V350Case11CutFre20.xls',
 'V300Case6CutFre20.xls',
 'V300Case26CutFre20.xls',
 'V350Case6CutFre20.xls',
 'V380Case1CutFre20.xls',
 'V300Case36CutFre20.xls',
 'V300Case11CutFre20.xls',
 'V300Case16CutFre20.xls',
 'V380Case6CutFre20.xls',
 'V300Case31CutFre20.xls',
 'V350Case1CutFre20.xls',
 'V300Case1CutFre20.xls',
 'V300Case21CutFre20.xls',
 'V380Case16CutFre20.xls',
 'V350Case16CutFre20.xls',
 'V350Case31CutFre20.xls',
 'V380Case31CutFre20.xls',
 'V380Case21CutFre20.xls',
 'V350Case21CutFre20.xls']

In [56]:
def get_files(pattern,path="Data"):
    files = [f for f in os.listdir(path) if re.match(pattern, f)]
    return files

In [57]:
get_files("*Fre20.xls")

error: nothing to repeat at position 0

In [42]:
def read_data(file_list=[],path="Data", cut_precent=0.05):
    if len(file_list)==0:
        print("No file to read!!")
        return
    
    df = pd.DataFrame(columns=['distance', 'acceleration','displacement', 'force'])
    for f in file_list:
        f_path = os.path.join(path,f)
        df_tmp = pd.read_excel(f_path)
        cut_idx= int(df_tmp.shape[0]*cut_precent)
        df_tmp.columns = ['distance', 'acceleration','displacement', 'force']
        df = pd.concat([df, df_tmp.iloc[cut_idx:df.shape[0]-cut_idx]])
        
    return df

In [46]:
df = read_data(["V300Case1CutFre20.xls","V300Case2CutFre50.xls"])

Data/V300Case1CutFre20.xls
Data/V300Case2CutFre50.xls

In [47]:
df.head()

       distance  acceleration  displacement       force
870  122.666667     -0.393284      0.071753  141.884098
871  122.750000     -0.682777      0.071805  143.375451
872  122.833333     -0.948500      0.071855  144.739334
873  122.916667     -1.187718      0.071905  145.958099
874  123.000000     -1.397972      0.071953  147.015645

In [48]:
df.shape

(29580, 4)